// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: grpcS.proto

#include "grpcS.pb.h"
#include "grpcS.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* grpcS_method_names[] = {
  "/grpcS/sayHello",
};

std::unique_ptr< grpcS::Stub> grpcS::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< grpcS::Stub> stub(new grpcS::Stub(channel, options));
  return stub;
}

grpcS::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_sayHello_(grpcS_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status grpcS::Stub::sayHello(::grpc::ClientContext* context, const ::Request& request, ::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Request, ::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_sayHello_, context, request, response);
}

void grpcS::Stub::async::sayHello(::grpc::ClientContext* context, const ::Request* request, ::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Request, ::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_sayHello_, context, request, response, std::move(f));
}

void grpcS::Stub::async::sayHello(::grpc::ClientContext* context, const ::Request* request, ::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_sayHello_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Response>* grpcS::Stub::PrepareAsyncsayHelloRaw(::grpc::ClientContext* context, const ::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Response, ::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_sayHello_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Response>* grpcS::Stub::AsyncsayHelloRaw(::grpc::ClientContext* context, const ::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsayHelloRaw(context, request, cq);
  result->StartCall();
  return result;
}

grpcS::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      grpcS_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< grpcS::Service, ::Request, ::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](grpcS::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Request* req,
             ::Response* resp) {
               return service->sayHello(ctx, req, resp);
             }, this)));
}

grpcS::Service::~Service() {
}

::grpc::Status grpcS::Service::sayHello(::grpc::ServerContext* context, const ::Request* request, ::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


